-- Admin API keys, created and revoked in Studio → API keys.
--
-- Until now the programmatic API had one secret, BLOG_API_TOKEN, held in an env
-- var: it could not be scoped (the blog writer's token could also export every
-- lead and delete content), could not be told apart from another consumer in
-- the audit log, and could not be revoked without a redeploy. A key here has a
-- name, a set of scopes (see src/lib/api-scopes.ts), an optional expiry, and is
-- revoked instantly.
--
-- Only a SHA-256 hash of the key is stored. The secret part is 32 random bytes,
-- so an unsalted fast hash is the right tool: there is nothing to brute-force,
-- and it is verified on every API request. `prefix` is the public lookup handle
-- shown in the UI and the audit log.
--
-- `created_by` is deliberately not a foreign key: a key must outlive the admin
-- who created it (deleting a teammate must not silently kill the integrations
-- they set up), and `created_by_email` keeps the record readable afterwards.
--
-- The app keeps working before this is applied: BLOG_API_TOKEN / LEADS_API_TOKEN
-- are still accepted, and Studio → API keys shows a notice instead of the list.
--
-- Idempotent.

CREATE TABLE IF NOT EXISTS public.api_keys (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             text        NOT NULL,
  prefix           text        NOT NULL UNIQUE,
  key_hash         text        NOT NULL,
  scopes           jsonb       NOT NULL DEFAULT '[]'::jsonb,
  created_by       integer,
  created_by_email text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  last_used_at     timestamptz,
  expires_at       timestamptz,
  revoked_at       timestamptz
);

-- Server-only table: default-deny for the PostgREST `anon` / `authenticated`
-- roles, same as the other internal tables (20260619_enable_rls_internal_tables).
-- The app connects as `postgres` (rolbypassrls), so it is unaffected.
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
